name: .NET Publish

on:
  push:
    branches: [ "main" ]
permissions:
  contents: write    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  version:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      PACKAGE_VERSION: ${{ steps.version-tag.outputs.package_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Increment Commit Tag
        id: version-tag
        run: |
          current_tag=$(git describe --abbrev=0 --tags)
          echo current tag: $current_tag
          major=$(echo $current_tag | cut -d "." -f 1 | cut -d "v" -f 2)
          minor=$(echo $current_tag | cut -d "." -f 2)
          patch=$(echo $current_tag | cut -d "." -f 3)
          new_patch=$((patch + 1))
          new_tag="v$major.$minor.$new_patch"
          package_version="$major.$minor.$new_patch"
          git tag $new_tag
          git push --tags
          echo "PACKAGE_VERSION=$package_version" >> $GITHUB_OUTPUT
  
  deploy:
    needs: 
    - test
    - version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Package Version
      run: echo ${{ needs.version.outputs.PACKAGE_VERSION }}
    - name: Pack
      working-directory: Dialog
      run: dotnet pack -c Release -o nuget -p:PackageVersion=${{ needs.version.outputs.PACKAGE_VERSION }}
    - name: Deploy Nuget
      working-directory: Dialog
      run: dotnet nuget push nuget/*.nupkg --skip-duplicate -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/marklauter/index.json
